#!/bin/bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NOTEBOOKS_DIR="$DIR/../notebooks"

NOTEBOOKS=( )

for FILE in $NOTEBOOKS_DIR/1-Intro/*.ipynb \
             $NOTEBOOKS_DIR/2-Preprocessing/*.ipynb \
             $NOTEBOOKS_DIR/3-Analysis/*.ipynb \
             $NOTEBOOKS_DIR/5-AdvancedTopics/*.ipynb; do

       FNAME=$(basename "$FILE")

       if [ $FNAME != "91-AtlanticTest.ipynb"          ] && # too long
          [ $FNAME != "02-Julia-introduction.ipynb"    ] && # to be completed by the user
          [ $FNAME != "03-netCDF-2Dimensions.ipynb"    ] && # to be completed by the user
          [ $FNAME != "08-data-downloading.ipynb"      ] && # requires email from user
          [ $FNAME != "90-full-analysis.ipynb"         ] && # too long
          [ $FNAME != "20-Turtles-Density-map.ipynb"   ] && # too long
          [ $FNAME != "BigBlackSea.ipynb"              ] && # too long
          [ $FNAME != "HeatmapsCV.ipynb"               ] && # too long
          [ $FNAME != "open-boundary-conditions.ipynb" ]; then  # too long
           NOTEBOOKS+=("$FILE")
       fi
done


echo testing "${NOTEBOOKS[@]}"

"$DIR/nbtest" "${NOTEBOOKS[@]}"



