#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        export PATH="/Users/travis/Library/Python/3.7/bin:$PATH";
    fi
    export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
fi

sed --version
echo $PATH
if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
julia --project --eval 'using Pkg; Pkg.instantiate();'
julia --project --eval 'using Pkg; Pkg.status();'
julia --project --eval 'using Pkg; Pkg.add(PackageSpec(name="DIVAnd", rev="master"));'
jupyter kernelspec list
utils/test-notebooks
