#!/bin/bash
# run as
# nbkversion <old julia version> <julia version> <notebook file>
# nbkversion 1.3.1 1.4.1 16-plot-results.ipynb

# in combination with find
# find notebooks/1-Intro/ notebooks/2-Preprocessing/ notebooks/3-Analysis/ notebooks/4-Postprocessing/ notebooks/5-AdvancedTopics/  -name "*ipynb" -exec utils/nbkversion 1.3.1 1.4.1 {} \;

JULIA_VERSION_OLD="$1"
JULIA_VERSION="$2"
FILE="$3"

JULIA_VERSION_XY=$(echo $JULIA_VERSION | cut  --delimiter='.' --field=1,2)

echo set "$FILE" to "$JULIA_VERSION"


perl -pi -e "s/\Q\"version\": \"$JULIA_VERSION_OLD\"/\"version\": \"$JULIA_VERSION\"/g" "$FILE"
sed --regexp-extended --in-place "s/julia-1.[0-9]/julia-$JULIA_VERSION_XY/g" "$FILE";
sed --regexp-extended --in-place "s/julia-1.[0-9]/julia-$JULIA_VERSION_XY/g" "$FILE";
sed --regexp-extended --in-place "s/Julia 1.[0-9].[0-9]/Julia $JULIA_VERSION/g" "$FILE";

