#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for i in $DIR/../notebooks/*.ipynb $DIR/../notebooks/*/*.ipynb; do
   echo running $(basename $i);
   jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=360 "$i"
done

