#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

JULIA_VERSION=$(julia --version | cut --delimiter=' ' --field=3);
JULIA_VERSION_XY=$(echo $JULIA_VERSION | cut  --delimiter='.' --field=1,2);
for i in $DIR/../notebooks/*.ipynb $DIR/../notebooks/*/*.ipynb; do
       fname=$(basename $i)

       if [ $fname != "91-AtlanticTest.ipynb" ] &&
          [ $fname != "20-Turtles-Density-map.ipynb" ] &&
          [ $fname != "13-processing-parameter-optimization.ipynb" ] &&
          [ $fname != "HeatmapsCV.ipynb" ] &&
          [ $fname != "Heatmaps.ipynb" ] &&
          [ $fname != "03-netCDF-2Dimensions.ipynb" ] &&
          [ $fname != "analysis-with-cycles.ipynb" ] &&
          [ $fname != "BigBlackSea.ipynb" ] &&
          [ $fname != "03-netCDF-2Dimensions.ipynb" ] &&
          [ $fname != "19_plot_results_basemap.ipynb" ]; then

           echo $i $JULIA_VERSION;
           sed --regexp-extended --in-place "s/julia-1.[0-9]/julia-$JULIA_VERSION_XY/g" "$i";
           sed --regexp-extended --in-place "s/Julia 1.[0-9].[0-9]/Julia $JULIA_VERSION/g" "$i";
           jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=360 "$i";
       fi
done

