name: Test homebrew

on: push

jobs:
  test1:
    name: Install commands
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install jupyter
        run: |
          brew update
          brew install jupyter
          brew upgrade

      - name: Check
        run: |
          jupyter --version
          jupyter-nbconvert --version